{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-actions-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-actions-runner.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-actions-runner.selectorLabels" . | nindent 6 }}
---
{{- if .Values.cloudflare.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-actions-runner.cloudflare.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-actions-runner.cloudflare.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-actions-runner.cloudflare.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
