{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-actions-runner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-actions-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
rules:
  # Manage runner Jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
  # Manage JIT config Secrets for runners
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-actions-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-actions-runner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-actions-runner.fullname" . }}
{{- end }}
