{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-actions-runner.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
type: Opaque
data:
  {{- if .Values.secrets.webhookSecret }}
  webhook-secret: {{ .Values.secrets.webhookSecret | b64enc | quote }}
  {{- else }}
  webhook-secret: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.githubToken }}
  github-token: {{ .Values.secrets.githubToken | b64enc | quote }}
  {{- else }}
  github-token: {{ "" | b64enc | quote }}
  {{- end }}
{{- end }}
