apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-actions-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kube-actions-runner.selectorLabels" . | nindent 4 }}
    app: webhook-scaler
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
